title: AirChoice Canada
description: Canadians for Increased International Airline Choice
url: "airchoicecanada.github.io"
baseurl: ""
timezone: America/Toronto
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

nav:
  - title: Home
    url: airchoicecanada.github.io
  - title: Data & Research
    url: airchoicecanada.github.io/data-research/
  - title: Get Involved
    url: airchoicecanada.github.io/get-involved/
  - title: Press Kit
    url: airchoicecanada.github.io/press-kit/

petition_url: "https://chng.it/yVwXDx77st"
mailchimp_url: "https://mailchi.mp/89cb1eda10ca/airchoice-mailing-list-signup"
form_endpoint: "https://usebasin.com/f/667134c544ab"
policy_paper_url: "https://drive.google.com/file/d/1l94fxM04K_P8gXf6QyWFrMv452TTdOHm/view?usp=drive_link"
policy_paper_fr_url: "https://drive.google.com/file/d/1odMcKcQDdhitYtAO9ofEAo_YAY25zk6l/view?usp=drive_link"