title: AirChoice Canada
description: Canadians for Increased International Airline Choice
url: "https://airchoice.ca"
baseurl: ""
timezone: America/Toronto
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

nav:
  - title: Home
    url: /
  - title: Data & Research
    url: /data-research/
  - title: Get Involved
    url: /get-involved/
  - title: Press Kit
    url: /press-kit/

petition_url: "https://www.change.org/AirChoiceCanada"
mailchimp_url: "https://mailchi.mp/89cb1eda10ca/airchoice-mailing-list-signup"
policy_paper_url: "https://drive.google.com/file/d/1l94fxM04K_P8gXf6QyWFrMv452TTdOHm/view?usp=drive_link&utm_source=website&utm_medium=pdf&utm_campaign=advocacy"
policy_paper_fr_url: "https://drive.google.com/file/d/1odMcKcQDdhitYtAO9ofEAo_YAY25zk6l/view?usp=drive_link&utm_source=website&utm_medium=pdf&utm_campaign=advocacy"

defaults:
  - scope:
      path: ""        # all files
    values:
      image: /assets/img/og/home-1200x630.png

twitter:
  username: AirChoiceCanada

brand:
  name: "AirChoice Canada"
  logo: "/assets/img/airchoice-logo-512.png"
  email: "info@airchoice.ca"
  same_as:
    - "https://x.com/AirChoiceCanada"
  contact_points:
    - contactType: "media relations"
      email: "info@airchoice.ca"
      availableLanguage: ["en","fr"]
      areaServed: "CA"
ga_measurement_id: "G-WF8VRQ9Y3G"